name: build-app

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest #ou specifier la version souhaitée.
    steps:
      - uses: actions/checkout@v3 # on récupère le code du repo.
      - run: npm install
      - run: npm run build
      - run: npm run e2e:headless