name: build-app

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest #ou specifier la version souhaitée.
    steps:
      - uses: actions/checkout@v3 # on récupère le code du repo.
      - run: npm install
      - run: npm run build

      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}