name: test-app

on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest #ou specifier la version souhaitée.
    steps:
      - uses: actions/checkout@v3 # on récupère le code du repo.
      - name: run tests
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm run e2e:headless

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: always() # meme si les run précédents fail, ça fera quand même l'action.
        with:
          name: e2e-tests
          path: cypress/videos